# Generated by Django 4.0.3 on 2022-04-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_inmueble_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
    ]
