# Generated by Django 4.0.3 on 2022-04-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_inmueble_descripcion_alter_inmueble_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='can_admin',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_list_inmuebles',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_list_propiedades',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_request_inmuebles',
        ),
    ]
