# Generated by Django 4.0.3 on 2022-04-12 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_inmuebletype_alter_inmueble_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(default='', max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(default='', max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.usertype')),
            ],
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='arrendador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='arrendatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrendatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
