# Generated by Django 4.0.3 on 2022-04-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_userprofile_alter_inmueble_arrendador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
