# Generated by Django 4.0.3 on 2022-04-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='segundo_nombre',
        ),
    ]
